# This file should be located in "ControlPanel/config.yaml"
# There is a symbolic link in "client/public/config.yaml"
# There is a symbolic link in "api/src/config.yaml"
# These are all the same file.

room_info:
  name: "Default"
  description: "Default description"
  subroom_1: "Default 1"
  subroom_2: "Default 2"

api:
  host: "192.168.254.187"
  port: 12413

client:
  host: "192.168.254.187"
  port: 52319

pi_nodes:
  - name: "callisto"
    ip: "192.168.254.201"
    location: "Living Room"
  - name: "aoede"
    ip: "192.168.254.200"
    location: "Living Room"

room_overrides: "TODO"

